const CURRICULUM = [
  {
    id: 'preA1-phonics',
    cefr: 'Pre-A1',
    title: 'English Sounds and Alphabet',
    objectives: ['Recognise English alphabet', 'Match letters to sounds', 'Practice simple phonics blending'],
    grammarFocus: 'Letter names vs. letter sounds',
    vocabularyFocus: ['Alphabet letters', 'Simple CVC words'],
    activityIdeas: ['Alphabet chant', 'Sound and picture matching', 'Build-a-word game'],
  },
  {
    id: 'preA1-greetings',
    cefr: 'Pre-A1',
    title: 'Greetings and Names',
    objectives: ['Say hello and goodbye', 'Ask and answer simple name questions', 'Introduce yourself'],
    grammarFocus: 'to be (I am, You are)',
    vocabularyFocus: ['hello', 'goodbye', 'my name is', 'what is your name'],
    activityIdeas: ['Role-play introductions', 'Greeting bingo', 'Name song'],
  },
  {
    id: 'preA1-numbers-colors',
    cefr: 'Pre-A1',
    title: 'Numbers and Colours',
    objectives: ['Count to ten', 'Name colours', 'Combine numbers and colours in phrases'],
    grammarFocus: 'There is/There are (singular)',
    vocabularyFocus: ['numbers 1-10', 'basic colours'],
    activityIdeas: ['Colour hunt', 'Counting claps', 'Colour-by-number worksheet'],
  },
  {
    id: 'preA1-family',
    cefr: 'Pre-A1',
    title: 'Family and Friends',
    objectives: ['Name close family members', 'Describe simple relationships', 'Use possessive adjectives'],
    grammarFocus: 'Possessive adjectives (my, your)',
    vocabularyFocus: ['mother', 'father', 'sister', 'friend'],
    activityIdeas: ['Family tree drawing', 'Guess who game', 'Flashcard races'],
  },
  {
    id: 'A1-classroom',
    cefr: 'A1',
    title: 'Classroom Language',
    objectives: ['Follow classroom instructions', 'Name school objects', 'Ask for help politely'],
    grammarFocus: 'Imperatives and can/can you',
    vocabularyFocus: ['pen', 'pencil', 'open', 'close', 'please'],
    activityIdeas: ['Simon says', 'Classroom scavenger hunt', 'Instruction relay'],
  },
  {
    id: 'A1-daily-routines',
    cefr: 'A1',
    title: 'Daily Routines',
    objectives: ['Talk about daily activities', 'Use simple present tense', 'Sequence events'],
    grammarFocus: 'Simple present (I wake up, I brush)',
    vocabularyFocus: ['wake up', 'brush teeth', 'go to school', 'have breakfast'],
    activityIdeas: ['Daily routine comic strip', 'Timeline matching', 'Guess the routine'],
  },
  {
    id: 'A1-food',
    cefr: 'A1',
    title: 'Food and Likes',
    objectives: ['Name common foods', 'Express likes and dislikes', 'Politely order food'],
    grammarFocus: 'Like/Don’t like; countable nouns',
    vocabularyFocus: ['fruits', 'vegetables', 'snacks', 'drinks'],
    activityIdeas: ['Menu role-play', 'Taste adjectives chart', 'Food memory game'],
  },
  {
    id: 'A1-people-descriptions',
    cefr: 'A1',
    title: 'Describing People',
    objectives: ['Use adjectives for appearance', 'Talk about height and hair', 'Use have/has'],
    grammarFocus: 'Have/has; be with adjectives',
    vocabularyFocus: ['tall', 'short', 'curly hair', 'eyes'],
    activityIdeas: ['Wanted poster', 'Guess who', 'Partner drawing dictation'],
  },
  {
    id: 'A1-hobbies',
    cefr: 'A1',
    title: 'Hobbies and Free Time',
    objectives: ['Name hobbies', 'Talk about frequency', 'Invite friends to activities'],
    grammarFocus: 'Present simple with adverbs of frequency',
    vocabularyFocus: ['play football', 'read books', 'once a week', 'often'],
    activityIdeas: ['Hobby interviews', 'Frequency chart', 'Plan a weekend role-play'],
  },
  {
    id: 'A2-shopping',
    cefr: 'A2',
    title: 'Shopping Conversations',
    objectives: ['Ask about prices', 'Request items', 'Handle polite transactions'],
    grammarFocus: 'How much/How many; countable vs. uncountable nouns',
    vocabularyFocus: ['price', 'expensive', 'cheap', 'cashier', 'coins'],
    activityIdeas: ['Role-play market stall', 'Budget challenge', 'Price tag matching'],
  },
  {
    id: 'A2-travel',
    cefr: 'A2',
    title: 'Travel and Directions',
    objectives: ['Ask for and give directions', 'Talk about transport', 'Describe travel plans'],
    grammarFocus: 'Imperatives; prepositions of place',
    vocabularyFocus: ['left', 'right', 'next to', 'bus', 'train'],
    activityIdeas: ['Map navigation task', 'Travel diary writing', 'Transport charades'],
  },
  {
    id: 'A2-weather',
    cefr: 'A2',
    title: 'Weather and Clothing',
    objectives: ['Describe weather patterns', 'Choose appropriate clothing', 'Discuss seasons'],
    grammarFocus: 'Adjectives and comparatives',
    vocabularyFocus: ['sunny', 'rainy', 'scarf', 'boots'],
    activityIdeas: ['Weather forecast presentation', 'Packing list game', 'Season wheel craft'],
  },
  {
    id: 'A2-health',
    cefr: 'A2',
    title: 'Health and Wellbeing',
    objectives: ['Talk about common illnesses', 'Give advice', 'Use should/shouldn’t'],
    grammarFocus: 'Modal verbs for advice',
    vocabularyFocus: ['headache', 'rest', 'medicine', 'doctor'],
    activityIdeas: ['Doctor and patient role-play', 'Healthy habits chart', 'Advice cards'],
  },
  {
    id: 'A2-storytelling',
    cefr: 'A2',
    title: 'Short Stories',
    objectives: ['Sequence past events', 'Use time connectors', 'Describe characters and settings'],
    grammarFocus: 'Past simple with time markers',
    vocabularyFocus: ['yesterday', 'then', 'after that', 'suddenly'],
    activityIdeas: ['Story cube prompts', 'Comic strip creation', 'Story circle sharing'],
  },
  {
    id: 'B1-environment',
    cefr: 'B1',
    title: 'Environment and Responsibility',
    objectives: ['Discuss environmental issues', 'Explain causes and effects', 'Propose solutions'],
    grammarFocus: 'First conditional; because/so',
    vocabularyFocus: ['recycle', 'pollution', 'climate', 'protect'],
    activityIdeas: ['Cause-effect chart', 'Poster campaign', 'Debate on solutions'],
  },
  {
    id: 'B1-technology',
    cefr: 'B1',
    title: 'Technology in Daily Life',
    objectives: ['Describe technology use', 'Compare devices', 'Talk about digital habits'],
    grammarFocus: 'Comparatives and superlatives review',
    vocabularyFocus: ['device', 'screen time', 'app', 'useful'],
    activityIdeas: ['Tech pros and cons table', 'Interview classmates', 'Design an app pitch'],
  },
  {
    id: 'B1-culture',
    cefr: 'B1',
    title: 'Culture and Traditions',
    objectives: ['Describe cultural events', 'Explain traditions', 'Compare celebrations'],
    grammarFocus: 'Past simple vs. present perfect',
    vocabularyFocus: ['tradition', 'festival', 'celebrate', 'custom'],
    activityIdeas: ['Culture showcase', 'Venn diagram comparisons', 'Story from heritage'],
  },
  {
    id: 'B1-goals',
    cefr: 'B1',
    title: 'Goals and Ambitions',
    objectives: ['Set personal goals', 'Discuss future plans', 'Motivate peers'],
    grammarFocus: 'Future forms (going to, will, would like to)',
    vocabularyFocus: ['ambition', 'plan', 'effort', 'achieve'],
    activityIdeas: ['Vision board creation', 'Goal interview', 'Action plan writing'],
  },
  {
    id: 'B1-critical-thinking',
    cefr: 'B1',
    title: 'Opinions and Arguments',
    objectives: ['Express clear opinions', 'Support ideas with reasons', 'React to others politely'],
    grammarFocus: 'Linking words (however, although, because)',
    vocabularyFocus: ['opinion', 'agree', 'disagree', 'perspective'],
    activityIdeas: ['Mini debates', 'Opinion ladder', 'Reason evidence match'],
  },
  {
    id: 'B1-storytelling-advanced',
    cefr: 'B1',
    title: 'Narratives with Detail',
    objectives: ['Use descriptive language', 'Build tension', 'Reflect on lessons learned'],
    grammarFocus: 'Past continuous with past simple',
    vocabularyFocus: ['suddenly', 'meanwhile', 'eventually', 'relieved'],
    activityIdeas: ['Story dice expansion', 'Peer feedback circles', 'Rewrite a fable'],
  }
];

module.exports = {
  CURRICULUM,
};
